"""it store cartridges and printers

Revision ID: 997f5eea8c0a
Revises: 
Create Date: 2019-10-10 10:15:07.635825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997f5eea8c0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartridge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cartridge_model', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartridge_cartridge_model'), 'cartridge', ['cartridge_model'], unique=True)
    op.create_index(op.f('ix_cartridge_color'), 'cartridge', ['color'], unique=False)
    op.create_table('office',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('place', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_name'), 'office', ['name'], unique=False)
    op.create_index(op.f('ix_office_place'), 'office', ['place'], unique=False)
    op.create_table('printer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('printer_model', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printer_brand'), 'printer', ['brand'], unique=False)
    op.create_index(op.f('ix_printer_printer_model'), 'printer', ['printer_model'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('cartridge_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('in_out', sa.Boolean(), nullable=True),
    sa.Column('office', sa.Integer(), nullable=True),
    sa.Column('printer', sa.Integer(), nullable=True),
    sa.Column('cartridge', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cartridge'], ['cartridge.id'], ),
    sa.ForeignKeyConstraint(['office'], ['office.id'], ),
    sa.ForeignKeyConstraint(['printer'], ['printer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartridge_stock_amount'), 'cartridge_stock', ['amount'], unique=False)
    op.create_index(op.f('ix_cartridge_stock_date'), 'cartridge_stock', ['date'], unique=False)
    op.create_table('cartridges',
    sa.Column('cartridge_id', sa.Integer(), nullable=True),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cartridge_id'], ['cartridge.id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], )
    )
    op.create_table('printer_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('in_out', sa.Boolean(), nullable=True),
    sa.Column('office', sa.Integer(), nullable=True),
    sa.Column('printer', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['office'], ['office.id'], ),
    sa.ForeignKeyConstraint(['printer'], ['printer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printer_stock_amount'), 'printer_stock', ['amount'], unique=False)
    op.create_index(op.f('ix_printer_stock_date'), 'printer_stock', ['date'], unique=False)
    op.create_table('printers',
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('printers')
    op.drop_index(op.f('ix_printer_stock_date'), table_name='printer_stock')
    op.drop_index(op.f('ix_printer_stock_amount'), table_name='printer_stock')
    op.drop_table('printer_stock')
    op.drop_table('cartridges')
    op.drop_index(op.f('ix_cartridge_stock_date'), table_name='cartridge_stock')
    op.drop_index(op.f('ix_cartridge_stock_amount'), table_name='cartridge_stock')
    op.drop_table('cartridge_stock')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_printer_printer_model'), table_name='printer')
    op.drop_index(op.f('ix_printer_brand'), table_name='printer')
    op.drop_table('printer')
    op.drop_index(op.f('ix_office_place'), table_name='office')
    op.drop_index(op.f('ix_office_name'), table_name='office')
    op.drop_table('office')
    op.drop_index(op.f('ix_cartridge_color'), table_name='cartridge')
    op.drop_index(op.f('ix_cartridge_cartridge_model'), table_name='cartridge')
    op.drop_table('cartridge')
    # ### end Alembic commands ###
