"""user roles

Revision ID: d447d6510b87
Revises: 997f5eea8c0a
Create Date: 2019-10-30 10:04:17.836444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd447d6510b87'
down_revision = '997f5eea8c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(None, 'cartridge_stock', type_='foreignkey')
    op.drop_column('cartridge_stock', 'printer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartridge_stock', sa.Column('printer', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'cartridge_stock', 'printer', ['printer'], ['id'])
    op.drop_table('user_roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
